SELECT
    fp.PRODUCT_ID,
    fp.PRODUCT_NAME,
    SUM(fp.PRICE * fo.AMOUNT) AS TOTAL_SALES
FROM
    FOOD_PRODUCT fp
INNER JOIN
    FOOD_ORDER fo
    ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE
    MONTH(fo.PRODUCE_DATE) = 5
GROUP BY
    fp.PRODUCT_ID,
    fp.PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC,
    fp.PRODUCT_ID ASC;