SELECT 
    RH.HISTORY_ID,
    FLOOR(
        CASE 
            WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 90 THEN C.DAILY_FEE * (1 - DP.DISCOUNT_RATE / 100) * (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1)
            WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 30 THEN C.DAILY_FEE * (1 - DP.DISCOUNT_RATE / 100) * (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1)
            WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 7 THEN C.DAILY_FEE * (1 - DP.DISCOUNT_RATE / 100) * (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1)
            ELSE C.DAILY_FEE * (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1)
        END
    ) AS FEE
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
JOIN 
    CAR_RENTAL_COMPANY_CAR C ON RH.CAR_ID = C.CAR_ID
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON C.CAR_TYPE = DP.CAR_TYPE
    AND CASE 
            WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 90 THEN DP.DURATION_TYPE = '90일 이상'
            WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 30 THEN DP.DURATION_TYPE = '30일 이상'
            WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 7 THEN DP.DURATION_TYPE = '7일 이상'
            ELSE DP.DURATION_TYPE IS NULL
        END
WHERE 
    C.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC, 
    RH.HISTORY_ID DESC;