SELECT FLAVOR
FROM (
    SELECT 
        FH.FLAVOR,
        SUM(FH.TOTAL_ORDER + COALESCE(J.TOTAL_ORDER, 0)) AS TOTAL_ORDER_SUM
    FROM FIRST_HALF FH
    LEFT JOIN JULY J
    ON FH.FLAVOR = J.FLAVOR
    GROUP BY FH.FLAVOR
    ORDER BY TOTAL_ORDER_SUM DESC
    LIMIT 3
) AS TOP_FLAVORS;