WITH RECURSIVE Hours AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM Hours
    WHERE HOUR < 23
)

SELECT
    h.HOUR,
    COUNT(a.ANIMAL_ID) AS COUNT
FROM
    Hours h
LEFT JOIN
    ANIMAL_OUTS a ON h.HOUR = HOUR(a.DATETIME)
GROUP BY
    h.HOUR
ORDER BY
    h.HOUR;